docs: remove `pip search` recommendation
This is no longer supported and will just error with:
```
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search).
Please use https://pypi.org/search (via a browser) instead. See
https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods
for more information.
```