Revert "test-bot: revise Step output transcoding and XML character filtering"
This reverts commit d002ed8dbfd03aa2483e5e055300adc3ae700a86.

```
==> git clean -ffdx
HEAD is now at d002ed8 test-bot: revise Step output transcoding and XML character filtering
Removing Library/Homebrew/test/.bundle/
Removing Library/Homebrew/test/fs_leak_log
Removing Library/Homebrew/test/vendor/
Error: invalid regular expression: /[^

 -uD7FFuE000-uFFFDu{10000}-u{10FFFF}]/
```
Using Ruby 1.8.