Revert "Enable patchelf.rb for HOMEBREW_DEVELOPERs."
This reverts commit 4dc1ee64d45af974bf237d91968b857c0eab9836.

Fix the error:
brew install patchelf
==> Pouring patchelf-0.10.x86_64_linux.bottle.1.tar.gz
Error: cannot load such file -- patchelf