dev-cmd/dispatch-build-bottle: add missing `require`
```
Error: uninitialized constant Homebrew::DevCmd::DispatchBuildBottle::Tap
Error: uninitialized constant Utils::Bottles
```

Signed-off-by: Rui Chen <rui@chenrui.dev>