sorbet: Fix (not) committing Spoom automatic sigil bumps
- This was failing to push the existing changes if there was nothing to
  commit. Add an extra `if`.

```
==> Bumping Sorbet `typed` sigils...
Checking files...

No file to bump from false to true
 Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)
[sorbet-files-update 7c3c04e94] sorbet: Update RBI files.
 1 file changed, 5 insertions(+), 1 deletion(-)
On branch sorbet-files-update
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```